# Generated by Django 4.2.6 on 2024-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0048_alter_revealrule_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='unofficial_status_type',
            field=models.CharField(choices=[('deadline_passed', 'DEADLINE_PASSED'), ('limit_exceeded', 'LIMIT_EXCEEDED')], default=None, max_length=32, null=True, verbose_name='LABEL_UNOFFICAL_STATUS_TYPE'),
        ),
    ]
